services:
  - type: web
    name: smart-itinerary-planning
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: dpg-db4l8dd9fdbs73fnibkg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: planning
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: planning
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        generateValue: true
